repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 253d99053f80e4a368175e93b36edb662e7e5135 # v1.109.1
    hooks:
      - id: terraform_fmt
        files: ^ubiquiti/.*\.(tf|tfvars)$
      - id: terraform_tflint
        files: ^ubiquiti/.*\.(tf|tfvars)$
      - id: terraform_validate
        files: ^ubiquiti/.*\.(tf|tfvars)$
      - id: terraform_trivy
        files: ^ubiquiti/.*\.(tf|tfvars)$
      - id: terraform_checkov
        files: ^ubiquiti/.*\.(tf|tfvars)$
      - id: terraform_docs
        files: ^ubiquiti/.*\.(tf|tfvars)$
        args: ["markdown", "table", "--output-file", "README.md", "./"]
