repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: 253d99053f80e4a368175e93b36edb662e7e5135 # v1.109.1
    hooks:
      - id: terraform_fmt
        files: &terraform_files \.(tf|tfvars)(\.json)?$
      - id: terraform_tflint
        files: *terraform_files
      - id: terraform_validate
        files: *terraform_files
      - id: terraform_trivy
        files: *terraform_files
      - id: terraform_checkov
        files: *terraform_files
      - id: terraform_docs
        files: ^ubiquiti/.*\.(tf|tfvars)$
        args:
          - --hook-config=--path-to-file=UBIQUITI_DOCS.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
      - id: terraform_docs
        files: ^proxmox/.*\.(tf|tfvars)$
        args:
          - --hook-config=--path-to-file=PROXMOX_DOCS.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true
